spring:
  application:
    name: demo6
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

oauth:
  client:
    id: ${GITHUB_CLIENT_ID}
    secret: ${GITHUB_CLIENT_SECRET}

---

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: user
    password: 1234
  config:
    activate:
      on-profile: test
  flyway:
    enabled: true
    baseline-on-migrate: false

oauth:
  client:
    id: 1
    secret: 1